# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ $default-branch, add_github_actions ]
  pull_request:
    branches: [ $default-branch ]

env:
  PLEXAPI_AUTH_SERVER_BASEURL: http://127.0.0.1:32400
  PLEX_CONTAINER_TAG: latest

jobs:
  plexapi-tests:
    name: PlexAPI Tests (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('requirements_dev.txt') }}
        restore-keys: ${{ runner.os }}-${{ matrix.python-version }}-pip-

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements_dev.txt
        pip install -e .

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 plexapi --count --select=E9,F63,F7,F82 --show-source --statistics
        # The GitHub editor is 127 chars wide
        flake8 plexapi --count --max-complexity=12 --max-line-length=127 --statistics

    - name: Bootstrap Plex server (unclaimed)
      run: |
        python \
          -u tools/plex-bootstraptest.py \
          --destination plex \
          --advertise-ip=127.0.0.1 \
          --bootstrap-timeout 540 \
          --docker-tag ${{ env.PLEX_CONTAINER_TAG }} \
          --unclaimed

    - name: Main tests with unclaimed server
      env:
        TEST_ACCOUNT_ONCE: 1
      run: |
        pytest \
          -rxXs \
          --ignore=tests/test_sync.py \
          --tb=native \
          --verbose \
          --cov=plexapi \
          tests 

    - name: Sync tests with unclaimed server
      env:
        PLEXAPI_HEADER_PROVIDES: 'controller,sync-target'
        PLEXAPI_HEADER_PLATFORM: iOS
        PLEXAPI_HEADER_PLATFORM_VERSION: 11.4.1
        PLEXAPI_HEADER_DEVICE: iPhone
      run: |
        pytest \
          -rxXs \
          --tb=native \
          --verbose \
          --cov=plexapi \
          --cov-append \
          tests/test_sync.py

    - name: Bootstrap Plex server (claimed)
      if: github.ref == 'refs/heads/master'
      env:
        PLEXAPI_AUTH_MYPLEX_USERNAME: ${{ secrets.PLEXAPI_AUTH_MYPLEX_USERNAME }}
        PLEXAPI_AUTH_MYPLEX_PASSWORD: ${{ secrets.PLEXAPI_AUTH_MYPLEX_PASSWORD }}
      run: |
        python \
          -u tools/plex-bootstraptest.py \
          --destination plex \
          --advertise-ip=127.0.0.1 \
          --bootstrap-timeout 540 \
          --docker-tag ${{ env.PLEX_CONTAINER_TAG }}

    - name: Main tests with claimed Plex server
      if: github.ref == 'refs/heads/master'
      run: |
        pytest \
          -rxXs \
          --ignore=tests/test_sync.py \
          --tb=native \
          --verbose \
          --cov=plexapi \
          tests 

    - name: Sync tests with claimed Plex server
      if: github.ref == 'refs/heads/master'
      env:
        PLEXAPI_HEADER_PROVIDES: 'controller,sync-target'
        PLEXAPI_HEADER_PLATFORM: iOS
        PLEXAPI_HEADER_PLATFORM_VERSION: 11.4.1
        PLEXAPI_HEADER_DEVICE: iPhone
      run: |
        pytest \
          -rxXs \
          --tb=native \
          --verbose \
          --cov=plexapi \
          --cov-append \
          tests/test_sync.py

    - name: Unlink PMS from MyPlex account
      if: github.ref == 'refs/heads/master'
      run: python -u tools/plex-teardowntest.py

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-${{ matrix.python-version }}
        path: .coverage

  coverage:
    name: Process Test Coverage
    runs-on: ubuntu-latest
    needs: plexapi-tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install coverage

    - name: Download all coverage artifacts
      uses: actions/download-artifact@v2

    - name: Combine coverage results
      run: |
        coverage combine coverage*/.coverage*
        coverage report --fail-under=50
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
